### ISSUE TITLE
[Issue]: OpenApi introspection throws error due to parameter name containing dashes

### ISSUE THREAD

**Issue by bgambocjaviniar** [wundergraph/wundergraph#1277]
### Description

When introspecting a yaml file of OpenAPI 3.0 using `openApi` of introspect from @wundergraph/sdk, it throws an error when a parameter contains dashes (`-`). 

For example:

```yaml
- name: some-param-name
   in: anything
   description: anything
```

Error thrown:

```json
{
  "level": "fatal",
  "time": 1695170818207,
  "pid": 4407,
  "hostname": "C02FQ2ZEMD6R",
  "component": "@wundergraph/sdk",
  "error": {
    "type": "GraphQLError",
    "message": "Syntax Error: Invalid number, expected digit but got: \"c\".",
    "stack": "GraphQLError: Syntax Error: Invalid number, expected digit but got: \"c\".\n 
    "locations": [{ "line": 36, "column": 55 }],
    "extensions": {}
  },
  "msg": "Syntax Error: Invalid number, expected digit but got: \"c\"."
}

```

# **Important note:**
- This error does not occur for openApiV2 of introspect from @wundergraph/sdk
- No errors related to this found using [swagger-editor ](https://github.com/swagger-api/swagger-editor)
- schemas were validated and generated using the [openapi generator from openapi tools](https://www.npmjs.com/package/@openapitools/openapi-generator-cli)

### Reproduction

- running `wunderctl generate` with the details below

Version:
`@wundergraph/sdk@0.167.1` 

wundergraph.config.ts:
```ts
const someNamespace = introspect.openApi({
  apiNamespace: 'someNamespace',
  source: {
    kind: 'file',
    filePath: '../shared-bff/specs/aopenapiv3specification.yaml',
  },
  baseURL: 'https://someUrl.com/',
  statusCodeUnions: true,
  headers: (builder) =>
    builder.addClientRequestHeader('Authorization', 'Authorization'),
});
```

aopenapiv3specification.yaml:

```yaml
...
paths:
     /some/path/userId:
       post:
            ...
            parameters:
            - name: some-param-name
               in: anything
               description: anything
...
```
