### ISSUE TITLE
[Issue]: OpenApi introspection throws error due to parameter's enum schemas

### ISSUE THREAD

**Issue by bgambocjaviniar** [wundergraph/wundergraph#1278]
### Description

When introspecting a yaml file of OpenAPI 3.0 using openApi of introspect from @wundergraph/sdk, it throws an error when a parameter for a path with schema of type string has enum 'string' boolean values.

For example:

```yaml
- name: some-param-name
   in: query
   description: anything
   schema:
        type: string
        default: "true"
        enum:
        - "true"
        - "false"
```

Error thrown:

```json
{
  "level": "fatal",
  "time": 1695170961007,
  "pid": 4558,
  "hostname": "C02FQ2ZEMD6R",
  "component": "@wundergraph/sdk",
  "error": {
    "type": "GraphQLError",
    "message": "Syntax Error: Name \"true\" is reserved and cannot be used for an enum value.",
    "stack": "GraphQLError: Syntax Error: Name \"true\" is reserved and cannot be used for an enum value.\n    at syntaxError 
    "locations": [{ "line": 1680, "column": 3 }],
    "extensions": {}
  },
  "msg": "Syntax Error: Name \"true\" is reserved and cannot be used for an enum value."
}

```

# **Important note:**
- This error does not occur for openApiV2 of introspect from @wundergraph/sdk
- No errors related to this found using [swagger-editor ](https://github.com/swagger-api/swagger-editor)
- schemas were validated and generated using the [openapi generator from openapi tools](https://www.npmjs.com/package/@openapitools/openapi-generator-cli)

### Reproduction

- running `wunderctl generate` with the details below

Version:
`@wundergraph/sdk@0.167.1` 

wundergraph.config.ts:
```ts
const someNamespace = introspect.openApi({
  apiNamespace: 'someNamespace',
  source: {
    kind: 'file',
    filePath: '../shared-bff/specs/aopenapiv3specification.yaml',
  },
  baseURL: 'https://someUrl.com/',
  statusCodeUnions: true,
  headers: (builder) =>
    builder.addClientRequestHeader('Authorization', 'Authorization'),
});
```

aopenapiv3specification.yaml:

```yaml
...
paths:
     /some/path/userId:
       post:
            ...
            parameters:
            - name: some-param-name
               in: query
               description: anything
               schema:
                  type: string
                  default: "true"
                  enum:
                  - "true"
                  - "false"
...
```
