### ISSUE TITLE
[Issue]: With openApiV2, BigInt cannot be serialized 

### ISSUE THREAD

**Issue by WeizhengSap** [wundergraph/wundergraph#1308]
### Description

We have one operation "CreateCartEntry". The request body is "OrderEntry". This is the spec:
```
post:
      tags:
      - Cart Entries
     ....
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/OrderEntry'
          application/json:
            schema:
              $ref: '#/components/schemas/OrderEntry'
        required: true
```

"OrderEntry" has property `quantity` which is init64:
```
 OrderEntry:
      type: object
      properties:
        ...
        quantity:
          type: integer
          description: Quantity number of items in order entry
          format: int64
```
My code to call the operation is this:
```
const { data, error } = await operations.mutate({
        operationName: 'occ/CreateCartEntry',
        input: {
          ...
          fields: 'DEFAULT',
          postBaseSiteIdUsersUserIdCartsCartIdEntriesInput: {
            quantity: 1,
            product: { code: productCode },
          },
        },
      });
```
With openApiV2, I get error of "Do not know how to serialize a BigInt":
![Screenshot 2023-10-05 at 4 21 32 PM](https://github.com/wundergraph/wundergraph/assets/44440575/3e38340c-26d5-478d-91ae-605a4ddb585e)

### Reproduction

check the description
