### ISSUE TITLE
Generated graphql Operations ignore the default values set in OAS Schema definition

### ISSUE THREAD

**Issue by uroslates** [wundergraph/wundergraph#1322]
## Problem

I'm working on an a Project where we're consuming **OAS based Schemas** (with a huge set of endpoints where the parameters have **default values specified whenever possible**). Wundergraph is used to generate the OAS Schema defined operations, which it does, but the issue is that the default values (specified in OAS Schemas **default** property) are ignored in generated operations!

This **degrades our DX significantly** - for most initial use-cases we would like our users to quickly generate and test generated operations W/O forcing them to provide all required query parameter values for queries/mutations **if they have defaults already specified within the OAS/GQL Spec**.

## Suggested solution

**Expectation:** It would be expected that if the OAS Schema (or GQL Specification Nodes) already contains the default values (for Queries/Mutations) they would also be taken into consideration and propagated (reflected) within the generated gql operations.

## Additional context

It would be expected that the output of the below OAS specification: 

```yaml
/pages:
    get:
      tags:
      - Pages
      summary: Retrieves all the pages matching the criteria
      operationId: getPages
      parameters:
      - name: currentPage
        in: query
        description: Current result page. Default value is 1.
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: pageSize
        in: query
        description: "Number of results returned per page. Default value: 10."
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      - name: pageType
        in: query
        description: Page type.
        required: false
        schema:
          type: string
          enum:
          - ContentPageType
          - ProductPageType
          - CategoryPageType
          default: ContentPageType
      - name: sort
        in: query
        description: Sorting method applied to the return results.
        required: false
        schema:
          type: string
          default: asc
```

would match the following graphql operation generated by Wundergraph:

```qraphql
# This file is auto generated.
# Remove/modify this header if you want to customize the operation.
query getPages_query($currentPage: Int = 1, $pageSize: Int = 10, $pageType: getPages_pageType = ContentPageTyoe, $sort: String = "asc") {
  getPages(
    currentPage: $currentPage
    pageSize: $pageSize
    pageType: $pageType
    sort: $sort
  ) {
   ...
}
```

Unfortunately currently generated oeprations do not respect the default values and generate the following operations:

```qraphql
# This file is auto generated.
# Remove/modify this header if you want to customize the operation.
query getPages_query($currentPage: Int, $pageSize: Int, $pageType: getPages_pageType, $sort: String) {
  getPages(
    currentPage: $currentPage
    pageSize: $pageSize
    pageType: $pageType
    sort: $sort
  ) {
   ...
}
```

I would be more than happy to submit the PR for this feature.
