### ISSUE TITLE
OpenAPI introspect problem when schema attribute not specified

### ISSUE THREAD

**Issue by remeq** [wundergraph/wundergraph#655]
### Bug description

We are getting following error when introspecting our OpenAPI spec:

```deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:840
            if (schema.oneOf && schema.oneOf.length === 1) {
                       ^

TypeError: Cannot read properties of undefined (reading 'oneOf')
    at RESTApiBuilder.resolveSingleSchemaOneOf (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:840:24)
    at RESTApiBuilder.traverseSchema (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:282:27)
    at /home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:188:22
    at Array.forEach (<anonymous>)
    at RESTApiBuilder.traversePath (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:183:54)
    at /home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:49:26
    at Array.forEach (<anonymous>)
    at RESTApiBuilder.build (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:43:42)
    at openApiSpecificationToRESTApiObject (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:30:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
 
### How to reproduce

After further investigation we found out that this error is shown when `schema` field is not present in input parameters for a path: for example WG fails if I have path like this:

```
  /backoffice/token/balance/{wallet_id}/hash/{token_hash}:
    get:
      tags:
        - crate
      description: ''
      operationId: get_balance_wallet
      parameters:
        - name: wallet_id
          in: path
          description: Wallet Id
          required: true
          deprecated: false
          schema:
            type: string
        - name: token_hash
          in: path
          description: Token hash
          required: true
          deprecated: false
```

This can be fixed by introducing `schema` field:

```
  /backoffice/token/balance/{wallet_id}/hash/{token_hash}:
    get:
      tags:
        - crate
      description: ''
      operationId: get_balance_wallet
      parameters:
        - name: wallet_id
          in: path
          description: Wallet Id
          required: true
          deprecated: false
          schema:
            type: string
        - name: token_hash
          in: path
          description: Token hash
          required: true
          deprecated: false
          schema:
            type: string
```
